id: 9524625b71884bb89956b08ec23d11e2
initial_creation_type: ocr
source_metadata:
  volumes:
    2cabd6e822b24b34a67249583456de9d:
      base_file: v066.txt
      image_group_id: I1PD95912
      title: འཕགས་པ་འདའ་ཀ་ཡེ་ཤེས་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོའི་འགྲེལ་པ།
      total_pages: 1529
      volume_number: 67
